/**
 * assurance.ts — typed view of the build-time assurance report.
 *
 * `assurance/data/assurance-report.json` is regenerated by the `assurance` CLI
 * (in CI and locally) and copied here. It is a build-time artifact — the score
 * folds in `forge coverage`, which only runs in CI — so the dashboard imports
 * it statically rather than over the live Supabase channel.
 */
import reportData from './data/assurance-report.json';

/** One component of the composite Assurance Score. */
export interface ScoreComponent {
  key: string;
  label: string;
  score: number;
  available: boolean;
  weight: number;
  detail: string;
  metrics: Record<string, number | string | boolean>;
}

/** How thoroughly an audit finding is covered by continuous assurance. */
export type CoverageTier =
  | 'fully-assured'
  | 'monitored-only'
  | 'harness-only'
  | 'gap'
  | 'not-applicable';

/** An audit finding resolved against the continuous-assurance layers. */
export interface ResolvedFinding {
  id: string;
  title: string;
  severity: string;
  status: string;
  category: string;
  securityRelevant: boolean;
  tier: CoverageTier;
  weight: number;
  layers: {
    invariants: number;
    harnessTests: number;
    liveMonitors: number;
    exploitReplays: number;
  };
  invariants: string[];
  harnessTests: string[];
  liveMonitors: string[];
  exploitReplays: string[];
  issues: string[];
}

/** One replayed exploit-class scenario. */
export interface ExploitScenario {
  id: string;
  name: string;
  exploitClass: string;
  reference: string;
  description: string;
  targetInvariants: string[];
  reverted: boolean;
  violatedInvariants: string[];
  attackerProfited: boolean;
  expectedOutcome: string;
  outcome: 'PREVENTED' | 'DETECTED' | 'MISSED';
}

/** One historical score snapshot. */
export interface HistoryEntry {
  at: string;
  gitSha: string | null;
  overall: number;
  grade: string;
}

/** The full assurance report. */
export interface AssuranceReport {
  generatedAt: string;
  gitSha: string | null;
  thesis: string;
  research: { citation: string; claim: string }[];
  score: {
    overall: number;
    grade: string;
    effectiveWeight: number;
    components: ScoreComponent[];
  };
  traceability: {
    summary: {
      totalFindings: number;
      securityRelevant: number;
      fullyAssured: number;
      monitoredOnly: number;
      harnessOnly: number;
      gaps: number;
      coveragePct: number;
    };
    findings: ResolvedFinding[];
    danglingReferences: string[];
  };
  exploits: {
    summary: {
      total: number;
      prevented: number;
      detected: number;
      missed: number;
      regressions: number;
      resistancePct: number;
    };
    scenarios: ExploitScenario[];
  };
  history: HistoryEntry[];
  gate: { minScore: number; passed: boolean; reasons: string[] };
}

/** The assurance report, loaded at build time. */
export const assuranceReport = reportData as unknown as AssuranceReport;
