/**
 * content.ts — plain-language + technical explanatory copy for every dashboard element.
 *
 * AUTO-GENERATED by the "guardian-dashboard-explainers" workflow: every item was
 * drafted from and then adversarially fact-checked against the repo sources
 * (README.md, docs/invariants.md, docs/assurance.md, the assurance report).
 * 52 items. Regenerate rather than editing prose by hand so the copy
 * stays traceable to those sources.
 */

export interface TipCopy {
  /** Short display name (used as the popover heading where helpful). */
  label?: string;
  /** Always-visible plain one-liner shown under a panel title. */
  subtitle?: string;
  /** Plain-language explanation — the always-on default layer. */
  plain: string;
  /** Precise technical detail — the on-demand layer. */
  technical?: string;
}

export type CopyKey =
  | "intro"
  | "panel:assurance-score"
  | "panel:invariant-health"
  | "panel:finding-traceability"
  | "panel:exploit-replay"
  | "panel:alert-feed"
  | "panel:detection-latency"
  | "INV-01"
  | "INV-02"
  | "INV-03"
  | "INV-04"
  | "INV-05"
  | "INV-06"
  | "INV-07"
  | "INV-08"
  | "INV-09"
  | "INV-10"
  | "INV-11"
  | "INV-12"
  | "amc:staticVerification"
  | "amc:exploitResistance"
  | "amc:findingTraceability"
  | "concept:amc"
  | "tier:fully-assured"
  | "tier:monitored-only"
  | "tier:harness-only"
  | "tier:gap"
  | "tier:not-applicable"
  | "outcome:PREVENTED"
  | "outcome:DETECTED"
  | "outcome:MISSED"
  | "chip:inv"
  | "chip:harness"
  | "chip:live"
  | "chip:replay"
  | "sev:High"
  | "sev:Medium"
  | "sev:Low"
  | "sev:Informational"
  | "topbar:latest-block"
  | "topbar:last-checked"
  | "topbar:avg-latency"
  | "topbar:guardian-live"
  | "topbar:vault-address"
  | "gl:invariant"
  | "gl:fuzz-campaign"
  | "gl:mirror-evaluator"
  | "gl:exploit-class"
  | "gl:vault"
  | "gl:base-sepolia"
  | "gl:detection-latency"
  | "gl:ci-gate";

export const COPY: Record<CopyKey, TipCopy> = {
  "intro": {"label":"How to read this","subtitle":"A live monitor that re-checks a demo lending vault's safety rules on Base testnet.","plain":"This is a live dashboard for a demo lending vault — a savings-and-loans contract — running on Base Sepolia, a free test network that holds no real money. A monitor re-checks 12 math-based safety rules (\"invariants\") and raises an alert when one breaks. To skim: scan the 12 invariants for anything failing, check the AMC score for how rigorously those checks were applied, and read the alerts feed for recent violations.","technical":"Foundry invariant fuzz campaign (2,000 runs) checks all 12 invariants pre-deploy; a TypeScript/viem monitor mirrors them 1:1 post-deploy; the AMC score grades the methodology in CI."},
  "panel:assurance-score": {"subtitle":"A 0-100 score of how thoroughly this project ran its own safety checks.","plain":"The AMC score rates how thoroughly the project ran its own safety checks — not whether the code is safe. It combines three parts: test coverage, replayed attacks, and traced findings. The project grades itself; the build fails below 80.","technical":"AMC = weighted mean of 3 pre-deployment components: static verification 45%, exploit resistance 35%, finding traceability 20%. Currently 94/100 (grade A). CI gates the build at >=80. Self-computed."},
  "panel:invariant-health": {"subtitle":"Live status of the 12 math rules that keep the vault solvent and honest.","plain":"Each card is one of the 12 safety rules the vault must always satisfy, like staying solvent. Healthy means it holds right now, violated means it broke, checking means the monitor hasn't evaluated it yet. They're re-checked block by block.","technical":"12 invariants (INV-01..12) evaluated per block by guardian/src/evaluator.ts, a 1:1 mirror of the Foundry invariant_* harness. Card status: HEALTHY (holds), VIOLATED, or CHECKING (not yet evaluated)."},
  "panel:finding-traceability": {"subtitle":"Shows every issue from the self-review is backed by a re-runnable check.","plain":"Every issue found in the project's own security review is linked here to the safety rule, test, and monitor check that covers it — and some also to a replayed attack. All 8 issues are fully covered today. The review is self-written, not an outside audit.","technical":"Resolves each security-review finding to >=1 invariant + harness test + monitor check (tier fully-assured). Currently 8/8 security-relevant findings fully assured, 100% weighted coverage."},
  "panel:exploit-replay": {"subtitle":"Re-runs famous DeFi hacks against the vault to see if it resists them.","plain":"Re-runs 10 famous DeFi attack types (like the Euler and Cream hacks) on the vault. Prevented means the code blocked it, detected means a rule caught it that block, missed means it got through. So far: 10 prevented, 0 missed.","technical":"10 exploit-class scenarios (EXP-01..10) replayed dual-surface: an attackable variant vs the canonical Vault. Outcome PREVENTED/DETECTED/MISSED per scenario. Currently 10 PREVENTED, 0 MISSED."},
  "panel:alert-feed": {"subtitle":"Live list of safety-rule breaks the monitor has spotted on-chain.","plain":"When the monitor finds one of the 12 safety rules breaking on the vault, it records the alert here: which rule broke, at which block, and the actual value versus the allowed limit. An empty feed means no violations were recorded.","technical":"Streams `alerts` rows the monitor persists to Supabase on a violation: invariant_id/name, block_number, actual_value vs bound_value, description, detection_latency_ms."},
  "panel:detection-latency": {"subtitle":"How quickly the monitor finishes checking each block, over time.","plain":"Each point shows how many milliseconds the monitor took to check all 12 rules for one block. A low, steady line means it's keeping up; spikes mean a check ran slow. It's a sign of how responsive the monitor is.","technical":"Sparkline of per-block check latency (latencyMs by blockNumber) from the monitor's `blocks_checked` heartbeats. Daemon mode runs ~2 s cadence; scheduled single-pass runs ~5 min."},
  "INV-01": {"label":"Protocol solvency","plain":"The vault always holds enough — idle cash plus the debt it's owed — to cover everything lenders are owed. If this breaks, the vault is insolvent and depositors could be unable to withdraw their money in full.","technical":"cash + totalBorrowed ≥ totalSupplyAssets. Class: Fuzz-tensioned — a wrong rounding direction breaks it."},
  "INV-02": {"label":"Supply-share integrity","plain":"Every lender's recorded stake adds up exactly to the vault's stored total. If the two drift apart, the books are wrong and a deposit could be miscounted, so you might be credited too little or too much.","technical":"totalSupplyShares = Σ userSupplyShares[i]. Class: Accounting identity — fuzzer regression-checks for a desync."},
  "INV-03": {"label":"Debt-share integrity","plain":"Every borrower's recorded debt adds up exactly to the vault's stored total of what's owed. If the two drift apart, the loan books are inconsistent and a borrower's debt could be mis-tracked — recorded as more or less than is really owed.","technical":"totalBorrowShares = Σ userBorrowShares[i]. Class: Accounting identity — fuzzer regression-checks for a desync."},
  "INV-04": {"label":"Lender-value floor","plain":"The value of a lender's stake can never fall below what they put in — interest only adds to it. If this broke, depositors could lose part of their original principal just by holding their position.","technical":"totalSupplyAssets ≥ totalSupplyShares. Class: Structural — non-trivial proof, confirmed empirically."},
  "INV-05": {"label":"Interest-index floor","plain":"The dial that tracks accumulated interest only ever moves forward, never backward. If it slipped back, borrowers' debts could be understated and lenders would be shortchanged on the interest they're owed.","technical":"borrowIndex ≥ 1e18. Class: Structural — true by construction; cheap regression check."},
  "INV-06": {"label":"No uncollateralised debt","plain":"Nobody can owe the vault money without collateral backing it. If this broke, the vault could pile up bad debt that no one can repay — a loss that ultimately falls on lenders.","technical":"∀u: userSupplyShares[u] == 0 ⇒ userDebt(u) == 0. Class: Fuzz-tensioned — guarded by withdraw/liquidate logic."},
  "INV-07": {"label":"Solvency monotonicity","plain":"The vault's safety cushion — assets beyond what lenders are owed — never shrinks from one check to the next. A drop would be an early warning that solvency is silently leaking, before it grows into a shortfall.","technical":"(totalAssets − totalSupplyAssets)_t ≥ (…)_{t−1}. Class: Fuzz-tensioned — load-bearing per test/mutant/MutantINV07.t.sol."},
  "INV-08": {"label":"Liquidation no-free-lunch","plain":"When an under-water loan is closed out, the liquidator can't grab more collateral than the debt repaid plus a fixed bonus. If broken, liquidators could over-seize and drain value belonging to other users.","technical":"seized · price · BPS ≤ paid · (BPS + bonus) · WAD. Class: Fuzz-tensioned — load-bearing per test/mutant/MutantINV08.t.sol."},
  "INV-09": {"label":"Debt monotonicity","plain":"If a borrower hasn't touched their loan, the amount they owe can only stay flat or grow with interest — never quietly shrink. A drop would mean debt is being erased, a loss that lenders would absorb.","technical":"userBorrowShares[a]_t = userBorrowShares[a]_{t−1} ⇒ userDebt(a)_t ≥ userDebt(a)_{t−1}. Class: Fuzz-tensioned — load-bearing per test/mutant/MutantINV09.t.sol."},
  "INV-10": {"label":"Debt rounding","plain":"Tiny rounding on each borrower's debt always favours the vault, so the per-loan amounts never sum to more than the booked total. If reversed, fractions could leak out of the vault, eroding solvency over time.","technical":"Σ userDebt[a] ≤ totalBorrowed. Class: Fuzz-tensioned — load-bearing per test/mutant/MutantINV10.t.sol."},
  "INV-11": {"label":"Oracle freshness","plain":"The vault refuses to act on a collateral price that has gone stale (more than a day old). If it didn't, it could lend or liquidate against an out-of-date price, letting someone exploit the gap from real value.","technical":"block.timestamp − oracle.lastUpdatedAt ≤ MAX_STALENESS (1 day). Class: Fuzz-tensioned — load-bearing per test/mutant/MutantINV11.t.sol."},
  "INV-12": {"label":"Accrue idempotence","plain":"Charging interest twice in the same moment has no extra effect — the second run does nothing. If it didn't, interest could be double-counted within one block, overcharging borrowers or distorting the books.","technical":"accrue(); accrue() ⇒ (borrowIndex, totalSupplyAssets, totalBorrowShares, lastAccrualTime) unchanged. Class: Fuzz-tensioned — load-bearing per test/mutant/MutantINV12.t.sol."},
  "amc:staticVerification": {"label":"Static Verification","subtitle":"How thoroughly the vault's code is exercised by tests and fuzzing.","plain":"How thoroughly the vault's code is tested before it ships — how many lines and decision-branches the tests reach, plus how hard automated fuzzing hammers it. Wider coverage means fewer untested corners where bugs can hide.","technical":"Weight 0.45. From `forge coverage` + `foundry.toml`: Vault.sol line/branch coverage + fuzz size (runs×depth→intensity). Live: 100% line, 88.9% branch, 2000×150."},
  "amc:exploitResistance": {"label":"Exploit Resistance","subtitle":"10 real-world DeFi attack classes replayed against the vault.","plain":"Replays of 10 known DeFi attack patterns — some drawn from real historical hacks, some from documented exploit classes — run against the vault to check whether its code blocks each one. It shows the testing method covers known attack patterns, on a testnet demo holding no real money.","technical":"Weight 0.35. From `test/exploit/`: 10 exploit-class replays run dual-surface (attackable vs canonical), scored by outcome. Live: 10 PREVENTED, 0 DETECTED, 0 MISSED → 100."},
  "amc:findingTraceability": {"label":"Finding Traceability","subtitle":"Share of review findings tied to a re-runnable check.","plain":"The share of security-review findings that are each tied to an automated check you can re-run — an invariant, a test, or a monitor rule — so no noted issue is left unverified.","technical":"Weight 0.20. From `security-review/findings.json`: weighted % of security-relevant findings bound to ≥1 re-runnable check (invariant/harness/monitor). Live: 100%, 0 gaps."},
  "concept:amc": {"label":"Assurance Methodology Coverage (AMC)","subtitle":"How rigorously the verification method was applied — not a safety guarantee.","plain":"A 0–100 score for how rigorously this project's own verification method was applied to the vault — not a promise the code is safe. A high number means the checks were run end-to-end, not that an outsider tried and failed to break it.","technical":"Weighted composite: 0.45 static + 0.35 exploit + 0.20 traceability on 0–100. The `assurance` CI job runs `npm run check -- --min-score 80` and fails the build below 80. Live: 94/100 (A)."},
  "tier:fully-assured": {"label":"Fully assured","plain":"A review finding covered three ways: a safety rule, a pre-deploy fuzz test, and a monitor check — the strongest coverage.","technical":"≥1 invariant + ≥1 harness test + a guardian/src/evaluator.ts monitor check all bind to the finding."},
  "tier:monitored-only": {"label":"Monitored only","plain":"Covered by the runtime monitor, but the pre-deploy fuzz tests can't prove it.","technical":"Has a guardian/src/evaluator.ts monitor check but no harness test that proves it."},
  "tier:harness-only": {"label":"Harness only","plain":"Proven by the pre-deploy fuzz tests, but the runtime monitor doesn't watch for it.","technical":"Covered by a Foundry harness invariant but has no guardian/src/evaluator.ts monitor check."},
  "tier:gap": {"label":"Gap","plain":"A security-relevant finding that no layer covers yet — a real hole to close.","technical":"Security-relevant finding bound to no invariant, harness test or monitor check."},
  "tier:not-applicable": {"label":"Not applicable","plain":"A non-security note (like gas usage) that doesn't need safety coverage.","technical":"Non-security finding (e.g. gas); not counted as security-relevant."},
  "outcome:PREVENTED": {"label":"Prevented","plain":"The vault's own code blocked the attack before any harm — nothing was corrupted.","technical":"Contract code blocked the attack; no state corruption, no invariant violated."},
  "outcome:DETECTED": {"label":"Detected","plain":"The attack did corrupt the vault, but a safety check caught it that same block.","technical":"State was corrupted but an invariant flagged it within the same block."},
  "outcome:MISSED": {"label":"Missed","plain":"Value was taken and no safety check noticed — a genuine gap. None happened here.","technical":"Value extracted with no invariant flagging it — a true gap. Replays so far: 0 MISSED."},
  "chip:inv": {"label":"Invariants","plain":"How many of the 12 math safety properties (invariants) cover this finding.","technical":"Count of invariants (INV-01…INV-12) bound to this finding."},
  "chip:harness": {"label":"Harness tests","plain":"How many pre-deploy fuzz tests exercise this finding.","technical":"Count of Foundry invariant_* harness tests bound to this finding."},
  "chip:live": {"label":"Monitor checks","plain":"How many runtime-monitor checks (in the deployable monitor) cover this finding.","technical":"Count of guardian/src/evaluator.ts checks bound to this finding (deployable, not necessarily live)."},
  "chip:replay": {"label":"Exploit replays","plain":"How many replayed historical-exploit tests touch this finding.","technical":"Count of EXP-01…EXP-10 exploit replays bound to this finding."},
  "sev:High": {"label":"High","plain":"The most serious rating in this project's self-conducted review — highest priority to fix.","technical":"Severity tag from security-review/findings.json; the highest of four review tiers."},
  "sev:Medium": {"label":"Medium","plain":"A mid-level rating in the self-review — worth fixing, but less urgent than High.","technical":"Severity tag from security-review/findings.json, one tier below High."},
  "sev:Low": {"label":"Low","plain":"A minor issue in the self-review — limited impact, low priority.","technical":"Severity tag from security-review/findings.json, above only Informational."},
  "sev:Informational": {"label":"Informational","plain":"The lowest severity rating in the self-review — least urgent of the four tiers, but here even these findings are still tracked as security-relevant.","technical":"Lowest severity tag in security-review/findings.json; here both Informational findings are flagged securityRelevant and resolved as fully-assured."},
  "topbar:latest-block": {"label":"Latest block","plain":"The most recent block (a numbered step of the Base Sepolia test blockchain) the monitor looked at. The higher it climbs, the more recent the on-chain data you're seeing.","technical":"Latest `block_number` from the newest `blocks_checked` row (Supabase) — the Base Sepolia head the Guardian monitor last evaluated all 12 invariants against."},
  "topbar:last-checked": {"label":"Last checked","plain":"How long ago the monitor last ran its safety checks. The scheduled job fires roughly every 5 minutes, so a recent time means it's keeping up; a stale one means a run was delayed or skipped.","technical":"`checked_at` of the newest `blocks_checked` row, written by the ~5-min scheduled GitHub Actions cron (`*/5`, `once.ts` single-pass); GitHub may delay or skip runs."},
  "topbar:avg-latency": {"label":"Avg latency","plain":"The average time one monitor check takes from start to finish, in milliseconds — finding accounts, reading the vault's state, and re-testing all 12 safety rules. It measures the monitor's own end-to-end work, including time spent waiting on network calls, not the blockchain's speed.","technical":"Mean of `latency_ms` over the most recent (~10) `blocks_checked` rows. Each value is one single-pass `once.ts` run's wall-clock (`Date.now()` delta from the run start) — account discovery via getLogs, vault-state fetch, and evaluation of all 12 invariants — so it includes RPC round-trips and deliberate rate-limit throttling, not just compute."},
  "topbar:guardian-live": {"label":"Guardian status","plain":"A live/down dot showing whether a fresh check arrived recently. 'Live' means the scheduled monitor is reporting; 'down' is normal between runs, since the free ~5-min job can be delayed or skipped.","technical":"Live/down dot from recency of the newest `blocks_checked` heartbeat; reflects the best-effort ~5-min GitHub Actions cron, not a real-time daemon — 'down' is expected between runs."},
  "topbar:vault-address": {"label":"Vault address","plain":"The on-chain address of the demo lending vault being watched — a public contract on Base Sepolia, Base's free test network. It holds no real money; this is a portfolio demo.","technical":"The monitored vault contract on Base Sepolia, set via `VITE_VAULT_ADDRESS`; the `vault` column on every `alerts`/`blocks_checked` row is scoped to this address."},
  "gl:invariant": {"label":"Invariant","plain":"A safety rule about the vault's math that must always stay true, no matter what users do — for example, the vault must always hold enough to cover what lenders are owed. If one breaks, something is wrong.","technical":"A mathematical safety property over vault state (e.g. `cash + totalBorrowed ≥ totalSupplyAssets`) asserted by an `invariant_*` function and re-checked off-chain; 12 are tracked."},
  "gl:fuzz-campaign": {"label":"Fuzz campaign (invariant fuzzing)","plain":"An automated test that hammers the vault with thousands of random sequences of actions, then checks that none of the safety rules broke — a way to surface bugs nobody thought to test by hand.","technical":"Foundry invariant fuzzing: a 2,000-run campaign (depth 150, up to ~300k handler calls) over 8 handlers; passes only if zero `invariant_*` assertions fail across the explored call sequences."},
  "gl:mirror-evaluator": {"label":"Mirror evaluator","plain":"The part of the runtime monitor that re-runs the exact same 12 safety checks on the live vault that were proven before launch — so what was tested and what is watched can never quietly drift apart.","technical":"`guardian/src/evaluator.ts` — a 1:1 port (`inv01`…`inv12`) of the harness `invariant_*` functions; discovers every account from vault events and reads each one's exact on-chain state, not a sampled proxy."},
  "gl:exploit-class": {"label":"Exploit class","plain":"A category of real-world attack that has drained other crypto lending projects (like faking a price, or acting on an out-of-date price) — the project replays 10 of them to check the demo vault resists the same trick.","technical":"A category of historical DeFi attack (Euler, Cream, bZx, Beanstalk classes); 10 replayed dual-surface vs an attackable variant and the canonical Vault, each scored PREVENTED/DETECTED/MISSED."},
  "gl:vault": {"label":"Lending vault","plain":"A demo lending pool: people lend one token to earn interest, and borrowers take loans against a different token they post as collateral. It is a teaching example on a test network — it holds no real money.","technical":"`Vault.sol`: an interest-bearing, over-collateralised two-asset lending vault (deposit/borrow/repay/liquidate/accrue) priced by a MockOracle; testnet teaching example, no reserve or governance."},
  "gl:base-sepolia": {"label":"Base Sepolia testnet","plain":"The test-network version of Base (a blockchain) where the demo vault and its tokens live — everything here is valueless play money, so nothing real is at stake. It exists for safe experimenting.","technical":"Base (an L2) test network where the demo `Vault` and tokens are deployed; the runtime monitor reads this public testnet vault and writes any violation to Supabase, which the dashboard displays. Holds no real value."},
  "gl:detection-latency": {"label":"Detection latency","plain":"How quickly the monitor flags a problem — the time, in milliseconds, between a check running and a broken safety rule being recorded as an alert. Lower means it noticed faster.","technical":"`detection_latency_ms` on an `alerts` row: the monitor's measured time in ms to detect a violation; the related `blocks_checked.latency_ms` feeds the dashboard latency sparkline."},
  "gl:ci-gate": {"label":"CI gate","plain":"An automatic check that runs on every code change and blocks it from being accepted if a rule isn't met — for example, the build fails if the assurance score drops below 80.","technical":"A pass/fail check in the GitHub Actions pipeline; e.g. `assurance` fails the build if AMC < 80, `coverage` gates `Vault.sol` ≥ 85% lines, `invariant-fuzz` fails on any `[FAIL]`."},
};

/** Lookup with a safe fallback so a missing key never crashes a panel. */
export function copy(key: CopyKey): TipCopy {
  return COPY[key] ?? { plain: "" };
}
